### ISSUE TITLE
os.startfile and subprocess.CREATE_NO_WINDOW are not supported in linux and macos

### ISSUE THREAD

**Issue by hor00s** [derto42/FlowBuddy#13]
## Erros:
1) In `GraphicsLauncher.ProcessThread.run` `AttributeError: module 'subprocess' has no attribute 'CREATE_NO_WINDOW'`
2) In `GraphicsLauncher.ProcessThread.run` `AttributeError: module 'os' has no attribute 'startfile'`
3) In `GraphicView.NewGroupDialog.render_groups` `AttributeError: module 'os' has no attribute 'startfile'`

These 3 errors appear in linux systems because `subprocess.CREATE_NO_WINDOW` as this is a [window only constant](https://docs.python.org/3/library/subprocess.html?highlight=subprocess#windows-constants) per Python docs as well as `os.startfile` [mentioned here](https://docs.python.org/3/library/os.html?highlight=os%20startfile#os.startfile)

## Solutions:
1) Redirect the output to '/dev/null' with `subprocess.DEVNULL` constant
2) Use `os.system` and run the file with `sudo python3 <script_path>` 
3)  Again, use `os.system` and run the file with `sudo python3 <script_path>`

**Comment by VasigaranAndAngel** [comment]
We have removed `os.startfile` and `subprocess.CREATE_NO_WINDOW` in commit ca561e89f6cb84a2ea5a06966ac3b9a8c9cef405.
Let me know if the errors are fixed. ❤️

**Comment by VasigaranAndAngel** [comment]
@hor00s Can you give us your discord ID so we can contact easier?

**Comment by VasigaranAndAngel** [comment]
Fixed on ca561e89f6cb84a2ea5a06966ac3b9a8c9cef405 commit.
