### ISSUE TITLE
GraphicLauncher.pyw seems to be missing as of last commit

### ISSUE THREAD

**Issue by DevBaddy** [derto42/FlowBuddy#17]
Hi,

Was interested into contributing to your project so I actually wanted to launch the application on my machine, because according to your documentation, the file that is missing was as of this commit: [https://github.com/derto42/FlowBuddy/commit/51e17a386dbf7f5c5b6c0dd19fe8863880afe89c](https://github.com/derto42/FlowBuddy/commit/51e17a386dbf7f5c5b6c0dd19fe8863880afe89c), was there in this repository some commits ago. Was this intentional or was this a mistake?

**Comment by derto42** [comment]
Sorry about that, the application now launches by running main.py


you can pull up the overlay by pressing “Ctrl and Backtick” after running it

**Comment by derto42** [comment]
Also please add me on discord Derto#9269

**Comment by DevBaddy** [comment]
Your Discord username is invalid.

**Comment by derto42** [comment]
Derto_#9269

**Comment by derto42** [comment]
forgot the underscore

**Comment by DevBaddy** [comment]
Sent a friend request.
