### ISSUE TITLE
App crashing after deleting multiple groups, pressing the button that enables buttons next to the group names

### ISSUE THREAD

**Issue by DevBaddy** [derto42/FlowBuddy#22]
Hi,

Noticed this bug where the app would just crash whenever you delete multiple groups in a matter of seconds. The app will also crash if you were to turn on the buttons next to the groups.

**Comment by DevBaddy** [comment]
Will be editing this issue a lot as I am noticing some scenarios where the app would crash.

**Comment by VasigaranAndAngel** [comment]
Fixed b4b8a06ac7b2ad77b5ffb3b3ffa1d8dba75a5393
