### ISSUE TITLE
Descriptions

### ISSUE THREAD

**Issue by np123-glitch** [derto42/FlowBuddy#30]
Hello everyone! I have been going through the Github page of FlowBuddy and I am seeing a lot of titles and issues without any descriptions to describe them. Half of the things that I see here I cannot understand. I think this is something that will increase the overall productivity of the team.

**Comment by VasigaranAndAngel** [comment]
have a look at them now.

**Comment by VasigaranAndAngel** [comment]
Thank you for the feedback.
