### ISSUE TITLE
Figure out why there seems to be a default spacing when margins are at 0.

### ISSUE THREAD

**Issue by derto42** [derto42/FlowBuddy#47]
For example, when changing the spacing above and below the tasks to 0, there still seems to be a little space between them when they should be technically touching.

Please figure out and let me know what is causing that. I would like the final UI spacings to be pixel perfect.

**Comment by VasigaranAndAngel** [comment]
maybe because of the default spacing of the pyqt layouts.

**Comment by derto42** [comment]
Workaround implemented, no longer needed.
