### ISSUE TITLE
UI keyboard navigation improvements. See comment.

### ISSUE THREAD

**Issue by derto42** [derto42/FlowBuddy#54]
1. When opening the group creation dialog, make the textbox become auto selected and ready for typing.

2. In the Task Creation dialog, make the text fields switchable by pressing TAB.

3. When creating/editing group or task - make ESC trigger the cancel button event. Right now Enter is configured to trigger the confirm event, see that for code reference.

**Comment by VasigaranAndAngel** [comment]
TAB triggers to change focus is built in.
ESC triggering cancel is already made.
