### ISSUE TITLE
Clicking through when clicking on icons.

### ISSUE THREAD

**Issue by derto42** [derto42/FlowBuddy#84]
When clicking towards the top of an addon icon in launcher it sometimes clicks through.

**Comment by VasigaranAndAngel** [comment]
need more details. maybe it's happening due to the `BaseWindow` context margin made for shadow.

**Comment by VasigaranAndAngel** [comment]
the lower widget is on top of the shortcuts widgets. thet's why the shortcuts are unclickable.
